version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: exemplo_senha
      POSTGRES_USER: exemplo_usuario
      POSTGRES_DB: social-network
    ports:
      - "5432:5432"